import {
  faBars,
  faBuilding,
  faCheckCircle,
  faChevronDown,
  faChevronUp,
  faEnvelope,
  faEye as faEyeSolid,
  faEyeSlash as faEyeSlashSolid,
  faExclamationCircle,
  faFileCsv,
  faFileExport,
  faHourglassHalf,
  faPen,
  faSort as faSortSolid,
  faSortUp as faSortUpSolid,
  faSortDown as faSortDownSolid,
  faUpload,
  faUserCheck,
  faUserPlus,
  faUserTimes,
  faLongArrowAltRight,
  faAngleLeft,
  faAngleRight,
  faChevronLeft,
  faChevronRight,
  faEye,
  faEyeSlash,
  faFilter,
  faPencilAlt,
  faRedo,
  faSearch,
  faSignOutAlt,
  faCloudUploadAlt,
  faQuestionCircle,
  faTimes,
  faTimesCircle,
  faUserSlash,
  faSort,
  faSortUp,
  faSortDown,
} from '@fortawesome/free-solid-svg-icons';

import { library } from '@fortawesome/fontawesome-svg-core';

library.add(
  faAngleLeft,
  faAngleRight,
  faBars,
  faBuilding,
  faCheckCircle,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faCloudUploadAlt,
  faEnvelope,
  faExclamationCircle,
  faEye,
  faEyeSlash,
  faEyeSolid,
  faEyeSlashSolid,
  faFileCsv,
  faFileExport,
  faFilter,
  faHourglassHalf,
  faLongArrowAltRight,
  faPen,
  faPencilAlt,
  faQuestionCircle,
  faRedo,
  faSearch,
  faSignOutAlt,
  faSort,
  faSortUp,
  faSortDown,
  faSortSolid,
  faSortUpSolid,
  faSortDownSolid,
  faTimes,
  faTimesCircle,
  faUpload,
  faUserCheck,
  faUserPlus,
  faUserTimes,
  faUserSlash
);
