import {
  faBars,
  faBuilding,
  faCheckCircle,
  faChevronDown,
  faChevronUp,
  faEnvelope,
  faEye as faEyeSolid,
  faEyeSlash as faEyeSlashSolid,
  faExclamationCircle,
  faFileCsv,
  faFileExport,
  faHourglassHalf,
  faPen,
  faUpload,
  faUserCheck,
  faUserPlus,
  faUserTimes,
} from '@fortawesome/free-solid-svg-icons';

import { faLongArrowRight, faPencil } from '@fortawesome/pro-solid-svg-icons';

import { faCloudUploadAlt } from '@fortawesome/pro-regular-svg-icons';

import {
  faAngleLeft,
  faAngleRight,
  faAngleDoubleLeft,
  faAngleDoubleRight,
  faChevronLeft,
  faChevronRight,
  faChevronDoubleLeft,
  faChevronDoubleRight,
  faEye,
  faEyeSlash,
  faFilter,
  faPencilAlt,
  faRedo,
  faSearch,
  faSignOut,
  faQuestionCircle,
  faTimes,
  faTimesCircle,
  faUserSlash,
  faSort,
  faSortUp,
  faSortDown,
} from '@fortawesome/pro-light-svg-icons';

import { library } from '@fortawesome/fontawesome-svg-core';

library.add(
  faAngleLeft,
  faAngleRight,
  faAngleDoubleLeft,
  faAngleDoubleRight,
  faBars,
  faBuilding,
  faCheckCircle,
  faChevronDoubleLeft,
  faChevronDoubleRight,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faCloudUploadAlt,
  faEnvelope,
  faExclamationCircle,
  faEye,
  faEyeSlash,
  faEyeSolid,
  faEyeSlashSolid,
  faFileCsv,
  faFileExport,
  faFilter,
  faHourglassHalf,
  faLongArrowRight,
  faPen,
  faPencil,
  faPencilAlt,
  faQuestionCircle,
  faRedo,
  faSearch,
  faSignOut,
  faSort,
  faSortUp,
  faSortDown,
  faTimes,
  faTimesCircle,
  faUpload,
  faUserCheck,
  faUserPlus,
  faUserTimes,
  faUserSlash
);
